Add tutorial for Kepler2D
kausalflow/hamilflow pull request #98
Opened 2024-09-16 21:15 UTC by emptymalei

Resolves #82

2024-09-23 17:12 UTC, cmp0xff requested changes
The tutorial shows the trajectory, which is solved by the textbook Kepler problem. However, it does not show our strength in that the trajectory is parameterised by time. For example, can we use colour to indicate the speed?

2024-09-23 17:12 UTC, cmp0xff commented on docs/tutorials/kepler_problem.py
> +# In this tutorial, we generate data for kepler problems.
```suggestion
# In this tutorial we will generate data for the Kepler problem.
```

2024-09-23 17:12 UTC, cmp0xff commented on docs/tutorials/kepler_problem.py
> +    )
```suggestion
    fig = px.line_polar(
        dataframe.assign(
            phi_degree=dataframe.phi / (2 * np.pi) * 360,
        ),
        r="r",
        theta="phi_degree",
        hover_data=["t", "r", "phi"],
        start_angle=0,
    )
```

2024-09-23 19:19 UTC, emptymalei commented
> The tutorial shows the trajectory, which is solved by the textbook Kepler problem. However, it does not show our strength in that the trajectory is parameterised by time. For example, can we use colour to indicate the speed?

good point. I added some animations.

2024-09-23 21:00 UTC, cmp0xff requested changes
The tutorial shows the basics and our strengths. I can approve it after this round of review.
- We need to fix the floating error when displaying `t`. Currently we see weird numbers like `-3.299999999`, `-3.199999999`, `-3.1`, etc. If I were writing the code, I would divide 1 by a power of 2.
- We can to make the animations more impressive.
  - We need to make them smoother.
  - For periodic orbits, we can do fewer revolutions.
  - For unbounded motion, we should somehow emphasise that the motion near the vertex is faster.

2024-09-24 19:28 UTC, cmp0xff approved these changes

2024-09-25 06:58 UTC, merged